class StoryScene extends Phaser.Scene {
    constructor() {
        super({ key: 'StoryScene' });
    }

    create() {
        const width = this.cameras.main.width;
        const height = this.cameras.main.height;

        // Black background
        this.add.rectangle(0, 0, width, height, 0x000000).setOrigin(0);

        const storyText =
            `Leto 2084.
Svet, kot smo ga poznali, je izginil.

Virus "Zmaj-Volka" je spremenil človeštvo.
Mesta so ruševine. Narava je divja.

Toda ti si drugačen.
Preživel si napad. Okužen, a imun.
Si HIBRID.

Zombiji te ne napadajo... čutijo te.
Zanje si ALFA.

Tvoja naloga:
1. Najdi izgubljeno sestro.
2. Maščuj starše.
3. Obnovi civilizacijo iz pepela.

Dobrodošel v KRVAVI ŽETVI.`;

        const textObj = this.add.text(width / 2, height + 100, storyText, {
            fontFamily: 'Courier New',
            fontSize: '24px',
            fill: '#00ff41',
            align: 'center',
            lineSpacing: 10
        });
        textObj.setOrigin(0.5, 0);

        // Scroll animation
        this.tweens.add({
            targets: textObj,
            y: 50,
            duration: 10000, // 10s scroll
            ease: 'Linear',
            onComplete: () => {
                this.time.delayedCall(2000, () => {
                    this.scene.start('GameScene');
                });
            }
        });

        // Skip instructions
        const skip = this.add.text(width - 20, height - 20, '[SPACE] Skip', {
            fontSize: '16px', fill: '#666'
        }).setOrigin(1);

        // Input to skip
        this.input.keyboard.on('keydown-SPACE', () => {
            this.scene.start('GameScene');
        });

        this.input.on('pointerdown', () => {
            this.scene.start('GameScene');
        });
    }
}
